// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: api/authservice/v1/service.proto

package authservice

import (
	context "context"
	fmt "fmt"
	proto "github.com/gogo/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

func init() { proto.RegisterFile("api/authservice/v1/service.proto", fileDescriptor_80c42cd25eb3e22a) }

var fileDescriptor_80c42cd25eb3e22a = []byte{
	// 478 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x95, 0x3f, 0x8f, 0xd3, 0x30,
	0x18, 0xc6, 0xe3, 0x85, 0x3f, 0x2e, 0x03, 0xb2, 0xc4, 0x72, 0x83, 0x85, 0x8e, 0xbb, 0xe3, 0xaf,
	0x12, 0x0a, 0x13, 0x30, 0xdd, 0x81, 0x74, 0x3a, 0x21, 0xa1, 0xaa, 0x50, 0x21, 0x55, 0x42, 0x34,
	0xa4, 0xaf, 0xd4, 0x48, 0x69, 0x12, 0x6c, 0x27, 0x52, 0x17, 0xc4, 0x47, 0x60, 0x65, 0x60, 0xe7,
	0xa3, 0x30, 0x76, 0xec, 0x48, 0xd3, 0x85, 0xb1, 0x1f, 0x01, 0xb5, 0x8e, 0x1d, 0xb7, 0x4d, 0x1d,
	0xb8, 0xad, 0x7d, 0xdf, 0xdf, 0xf3, 0x3c, 0xaf, 0x5f, 0x47, 0x32, 0xbe, 0xed, 0xa7, 0xa1, 0xe7,
	0x67, 0x62, 0xc4, 0x81, 0xe5, 0x61, 0x00, 0x5e, 0xde, 0xf6, 0xca, 0x9f, 0x6e, 0xca, 0x12, 0x91,
	0x10, 0xe2, 0xa7, 0xa1, 0x6b, 0x10, 0x6e, 0xde, 0x3e, 0xb8, 0x5f, 0xa3, 0x62, 0xf0, 0x39, 0x03,
	0x2e, 0x3e, 0x32, 0xe0, 0x69, 0x12, 0xf3, 0x52, 0xfe, 0xe4, 0x47, 0x0b, 0xb7, 0x4e, 0x33, 0x31,
	0x7a, 0x2b, 0x49, 0xf2, 0x0e, 0x5f, 0x3d, 0x07, 0xd1, 0x4d, 0x22, 0x20, 0x87, 0xee, 0xae, 0xb5,
	0x5b, 0x36, 0xbb, 0xd2, 0xed, 0xe0, 0x8e, 0x95, 0x91, 0x49, 0x87, 0x0e, 0x79, 0x8f, 0xaf, 0x95,
	0x45, 0x4e, 0x6c, 0x12, 0xae, 0x7c, 0x8f, 0xec, 0x90, 0x36, 0xfe, 0x82, 0x6f, 0xa9, 0xea, 0xd9,
	0xa4, 0x03, 0x6c, 0x1c, 0x72, 0x1e, 0x26, 0x31, 0x27, 0x8f, 0x6d, 0x06, 0x1b, 0xa8, 0x8a, 0x6c,
	0xff, 0x87, 0x62, 0xeb, 0x60, 0x3d, 0x0e, 0x6c, 0xff, 0xc1, 0xd6, 0xdd, 0xa6, 0x83, 0x95, 0x90,
	0x36, 0x96, 0xf7, 0xb0, 0xaa, 0xee, 0xbd, 0x87, 0x55, 0xb3, 0xe9, 0x1e, 0x24, 0xa3, 0x5d, 0x07,
	0xb8, 0x75, 0x11, 0xe7, 0xa1, 0x00, 0x39, 0xf1, 0x49, 0x9d, 0xca, 0x00, 0x94, 0xfb, 0xdd, 0x46,
	0x4e, 0x27, 0x24, 0xf8, 0x66, 0x17, 0x38, 0xc4, 0xc3, 0x55, 0x43, 0x22, 0xe4, 0x61, 0x9d, 0x7c,
	0x9b, 0x52, 0x59, 0x8f, 0xfe, 0x0d, 0xd6, 0x81, 0x1f, 0x30, 0xee, 0xa5, 0x43, 0x5f, 0x4e, 0x42,
	0x8e, 0xeb, 0xd4, 0x55, 0x5f, 0x85, 0x9c, 0x34, 0x61, 0xa6, 0xfd, 0x2b, 0x88, 0xc0, 0x66, 0x5f,
	0xf5, 0xad, 0xf6, 0x26, 0xa6, 0xed, 0xbf, 0x23, 0x4c, 0xab, 0xdc, 0x37, 0xfe, 0x18, 0x78, 0xea,
	0x07, 0x60, 0x7e, 0xc9, 0xcf, 0xec, 0xb3, 0xd6, 0x69, 0xd4, 0x1c, 0xcf, 0x2f, 0x23, 0xd5, 0xb3,
	0x05, 0xf8, 0xc6, 0x4b, 0x06, 0xbe, 0x80, 0xd3, 0xce, 0xc5, 0x6b, 0x98, 0x90, 0xda, 0xaf, 0xc0,
	0x24, 0x54, 0xec, 0xbd, 0x66, 0xd0, 0xdc, 0xef, 0x39, 0x08, 0x59, 0xe6, 0xf5, 0xfb, 0xad, 0xfa,
	0xd6, 0xfd, 0x9a, 0x98, 0xb6, 0xef, 0xe3, 0xeb, 0xba, 0x4e, 0x8e, 0xac, 0x32, 0x65, 0x7e, 0xdc,
	0x40, 0x99, 0xfb, 0x91, 0x77, 0x6a, 0xdb, 0x8f, 0x49, 0x58, 0xf7, 0xb3, 0x09, 0xaa, 0x90, 0xb3,
	0xc1, 0x74, 0x4e, 0x9d, 0xd9, 0x9c, 0x3a, 0xcb, 0x39, 0x45, 0x5f, 0x0b, 0x8a, 0x7e, 0x16, 0x14,
	0xfd, 0x2a, 0x28, 0x9a, 0x16, 0x14, 0xfd, 0x2e, 0x28, 0xfa, 0x53, 0x50, 0x67, 0x59, 0x50, 0xf4,
	0x6d, 0x41, 0x9d, 0xe9, 0x82, 0x3a, 0xb3, 0x05, 0x75, 0xfa, 0x0f, 0xc4, 0x38, 0x65, 0x91, 0x1b,
	0x44, 0x49, 0x36, 0xf4, 0x76, 0x1f, 0x83, 0x17, 0xc6, 0xdf, 0x4f, 0x57, 0xd6, 0x0f, 0xc1, 0xd3,
	0xbf, 0x01, 0x00, 0x00, 0xff, 0xff, 0x74, 0x67, 0x50, 0x60, 0x6b, 0x06, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// AuthServiceClient is the client API for AuthService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type AuthServiceClient interface {
	GetRole(ctx context.Context, in *GetRoleRequest, opts ...grpc.CallOption) (*GetRoleResponse, error)
	GetRoles(ctx context.Context, in *GetRolesRequest, opts ...grpc.CallOption) (*GetRolesResponse, error)
	GetRolesByPermissions(ctx context.Context, in *GetRolesByPermissionsRequest, opts ...grpc.CallOption) (*GetRolesByPermissionsResponse, error)
	GetUsers(ctx context.Context, in *GetUsersRequest, opts ...grpc.CallOption) (*GetUsersResponse, error)
	GetUser(ctx context.Context, in *GetUserRequest, opts ...grpc.CallOption) (*GetUserResponse, error)
	InviteUsers(ctx context.Context, in *InviteUsersRequest, opts ...grpc.CallOption) (*InviteUsersResponse, error)
	ResendUserInvite(ctx context.Context, in *ResendUserInviteRequest, opts ...grpc.CallOption) (*ResendUserInviteResponse, error)
	UpdateUser(ctx context.Context, in *UpdateUserRequest, opts ...grpc.CallOption) (*UpdateUserResponse, error)
	DeleteUser(ctx context.Context, in *DeleteUserRequest, opts ...grpc.CallOption) (*DeleteUserResponse, error)
	UpdateUserNamespacePermissions(ctx context.Context, in *UpdateUserNamespacePermissionsRequest, opts ...grpc.CallOption) (*UpdateUserNamespacePermissionsResponse, error)
	CreateAPIKey(ctx context.Context, in *CreateAPIKeyRequest, opts ...grpc.CallOption) (*CreateAPIKeyResponse, error)
	GetAPIKeys(ctx context.Context, in *GetAPIKeysRequest, opts ...grpc.CallOption) (*GetAPIKeysResponse, error)
	GetAPIKey(ctx context.Context, in *GetAPIKeyRequest, opts ...grpc.CallOption) (*GetAPIKeyResponse, error)
	DeleteAPIKey(ctx context.Context, in *DeleteAPIKeyRequest, opts ...grpc.CallOption) (*DeleteAPIKeyResponse, error)
}

type authServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAuthServiceClient(cc grpc.ClientConnInterface) AuthServiceClient {
	return &authServiceClient{cc}
}

func (c *authServiceClient) GetRole(ctx context.Context, in *GetRoleRequest, opts ...grpc.CallOption) (*GetRoleResponse, error) {
	out := new(GetRoleResponse)
	err := c.cc.Invoke(ctx, "/api.authservice.v1.AuthService/GetRole", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authServiceClient) GetRoles(ctx context.Context, in *GetRolesRequest, opts ...grpc.CallOption) (*GetRolesResponse, error) {
	out := new(GetRolesResponse)
	err := c.cc.Invoke(ctx, "/api.authservice.v1.AuthService/GetRoles", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authServiceClient) GetRolesByPermissions(ctx context.Context, in *GetRolesByPermissionsRequest, opts ...grpc.CallOption) (*GetRolesByPermissionsResponse, error) {
	out := new(GetRolesByPermissionsResponse)
	err := c.cc.Invoke(ctx, "/api.authservice.v1.AuthService/GetRolesByPermissions", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authServiceClient) GetUsers(ctx context.Context, in *GetUsersRequest, opts ...grpc.CallOption) (*GetUsersResponse, error) {
	out := new(GetUsersResponse)
	err := c.cc.Invoke(ctx, "/api.authservice.v1.AuthService/GetUsers", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authServiceClient) GetUser(ctx context.Context, in *GetUserRequest, opts ...grpc.CallOption) (*GetUserResponse, error) {
	out := new(GetUserResponse)
	err := c.cc.Invoke(ctx, "/api.authservice.v1.AuthService/GetUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authServiceClient) InviteUsers(ctx context.Context, in *InviteUsersRequest, opts ...grpc.CallOption) (*InviteUsersResponse, error) {
	out := new(InviteUsersResponse)
	err := c.cc.Invoke(ctx, "/api.authservice.v1.AuthService/InviteUsers", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authServiceClient) ResendUserInvite(ctx context.Context, in *ResendUserInviteRequest, opts ...grpc.CallOption) (*ResendUserInviteResponse, error) {
	out := new(ResendUserInviteResponse)
	err := c.cc.Invoke(ctx, "/api.authservice.v1.AuthService/ResendUserInvite", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authServiceClient) UpdateUser(ctx context.Context, in *UpdateUserRequest, opts ...grpc.CallOption) (*UpdateUserResponse, error) {
	out := new(UpdateUserResponse)
	err := c.cc.Invoke(ctx, "/api.authservice.v1.AuthService/UpdateUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authServiceClient) DeleteUser(ctx context.Context, in *DeleteUserRequest, opts ...grpc.CallOption) (*DeleteUserResponse, error) {
	out := new(DeleteUserResponse)
	err := c.cc.Invoke(ctx, "/api.authservice.v1.AuthService/DeleteUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authServiceClient) UpdateUserNamespacePermissions(ctx context.Context, in *UpdateUserNamespacePermissionsRequest, opts ...grpc.CallOption) (*UpdateUserNamespacePermissionsResponse, error) {
	out := new(UpdateUserNamespacePermissionsResponse)
	err := c.cc.Invoke(ctx, "/api.authservice.v1.AuthService/UpdateUserNamespacePermissions", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authServiceClient) CreateAPIKey(ctx context.Context, in *CreateAPIKeyRequest, opts ...grpc.CallOption) (*CreateAPIKeyResponse, error) {
	out := new(CreateAPIKeyResponse)
	err := c.cc.Invoke(ctx, "/api.authservice.v1.AuthService/CreateAPIKey", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authServiceClient) GetAPIKeys(ctx context.Context, in *GetAPIKeysRequest, opts ...grpc.CallOption) (*GetAPIKeysResponse, error) {
	out := new(GetAPIKeysResponse)
	err := c.cc.Invoke(ctx, "/api.authservice.v1.AuthService/GetAPIKeys", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authServiceClient) GetAPIKey(ctx context.Context, in *GetAPIKeyRequest, opts ...grpc.CallOption) (*GetAPIKeyResponse, error) {
	out := new(GetAPIKeyResponse)
	err := c.cc.Invoke(ctx, "/api.authservice.v1.AuthService/GetAPIKey", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authServiceClient) DeleteAPIKey(ctx context.Context, in *DeleteAPIKeyRequest, opts ...grpc.CallOption) (*DeleteAPIKeyResponse, error) {
	out := new(DeleteAPIKeyResponse)
	err := c.cc.Invoke(ctx, "/api.authservice.v1.AuthService/DeleteAPIKey", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AuthServiceServer is the server API for AuthService service.
type AuthServiceServer interface {
	GetRole(context.Context, *GetRoleRequest) (*GetRoleResponse, error)
	GetRoles(context.Context, *GetRolesRequest) (*GetRolesResponse, error)
	GetRolesByPermissions(context.Context, *GetRolesByPermissionsRequest) (*GetRolesByPermissionsResponse, error)
	GetUsers(context.Context, *GetUsersRequest) (*GetUsersResponse, error)
	GetUser(context.Context, *GetUserRequest) (*GetUserResponse, error)
	InviteUsers(context.Context, *InviteUsersRequest) (*InviteUsersResponse, error)
	ResendUserInvite(context.Context, *ResendUserInviteRequest) (*ResendUserInviteResponse, error)
	UpdateUser(context.Context, *UpdateUserRequest) (*UpdateUserResponse, error)
	DeleteUser(context.Context, *DeleteUserRequest) (*DeleteUserResponse, error)
	UpdateUserNamespacePermissions(context.Context, *UpdateUserNamespacePermissionsRequest) (*UpdateUserNamespacePermissionsResponse, error)
	CreateAPIKey(context.Context, *CreateAPIKeyRequest) (*CreateAPIKeyResponse, error)
	GetAPIKeys(context.Context, *GetAPIKeysRequest) (*GetAPIKeysResponse, error)
	GetAPIKey(context.Context, *GetAPIKeyRequest) (*GetAPIKeyResponse, error)
	DeleteAPIKey(context.Context, *DeleteAPIKeyRequest) (*DeleteAPIKeyResponse, error)
}

// UnimplementedAuthServiceServer can be embedded to have forward compatible implementations.
type UnimplementedAuthServiceServer struct {
}

func (*UnimplementedAuthServiceServer) GetRole(ctx context.Context, req *GetRoleRequest) (*GetRoleResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetRole not implemented")
}
func (*UnimplementedAuthServiceServer) GetRoles(ctx context.Context, req *GetRolesRequest) (*GetRolesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetRoles not implemented")
}
func (*UnimplementedAuthServiceServer) GetRolesByPermissions(ctx context.Context, req *GetRolesByPermissionsRequest) (*GetRolesByPermissionsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetRolesByPermissions not implemented")
}
func (*UnimplementedAuthServiceServer) GetUsers(ctx context.Context, req *GetUsersRequest) (*GetUsersResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUsers not implemented")
}
func (*UnimplementedAuthServiceServer) GetUser(ctx context.Context, req *GetUserRequest) (*GetUserResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUser not implemented")
}
func (*UnimplementedAuthServiceServer) InviteUsers(ctx context.Context, req *InviteUsersRequest) (*InviteUsersResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method InviteUsers not implemented")
}
func (*UnimplementedAuthServiceServer) ResendUserInvite(ctx context.Context, req *ResendUserInviteRequest) (*ResendUserInviteResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ResendUserInvite not implemented")
}
func (*UnimplementedAuthServiceServer) UpdateUser(ctx context.Context, req *UpdateUserRequest) (*UpdateUserResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateUser not implemented")
}
func (*UnimplementedAuthServiceServer) DeleteUser(ctx context.Context, req *DeleteUserRequest) (*DeleteUserResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteUser not implemented")
}
func (*UnimplementedAuthServiceServer) UpdateUserNamespacePermissions(ctx context.Context, req *UpdateUserNamespacePermissionsRequest) (*UpdateUserNamespacePermissionsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateUserNamespacePermissions not implemented")
}
func (*UnimplementedAuthServiceServer) CreateAPIKey(ctx context.Context, req *CreateAPIKeyRequest) (*CreateAPIKeyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateAPIKey not implemented")
}
func (*UnimplementedAuthServiceServer) GetAPIKeys(ctx context.Context, req *GetAPIKeysRequest) (*GetAPIKeysResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAPIKeys not implemented")
}
func (*UnimplementedAuthServiceServer) GetAPIKey(ctx context.Context, req *GetAPIKeyRequest) (*GetAPIKeyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAPIKey not implemented")
}
func (*UnimplementedAuthServiceServer) DeleteAPIKey(ctx context.Context, req *DeleteAPIKeyRequest) (*DeleteAPIKeyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteAPIKey not implemented")
}

func RegisterAuthServiceServer(s *grpc.Server, srv AuthServiceServer) {
	s.RegisterService(&_AuthService_serviceDesc, srv)
}

func _AuthService_GetRole_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRoleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).GetRole(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.authservice.v1.AuthService/GetRole",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).GetRole(ctx, req.(*GetRoleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthService_GetRoles_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRolesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).GetRoles(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.authservice.v1.AuthService/GetRoles",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).GetRoles(ctx, req.(*GetRolesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthService_GetRolesByPermissions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRolesByPermissionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).GetRolesByPermissions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.authservice.v1.AuthService/GetRolesByPermissions",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).GetRolesByPermissions(ctx, req.(*GetRolesByPermissionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthService_GetUsers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUsersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).GetUsers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.authservice.v1.AuthService/GetUsers",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).GetUsers(ctx, req.(*GetUsersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthService_GetUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).GetUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.authservice.v1.AuthService/GetUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).GetUser(ctx, req.(*GetUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthService_InviteUsers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InviteUsersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).InviteUsers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.authservice.v1.AuthService/InviteUsers",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).InviteUsers(ctx, req.(*InviteUsersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthService_ResendUserInvite_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResendUserInviteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).ResendUserInvite(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.authservice.v1.AuthService/ResendUserInvite",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).ResendUserInvite(ctx, req.(*ResendUserInviteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthService_UpdateUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).UpdateUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.authservice.v1.AuthService/UpdateUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).UpdateUser(ctx, req.(*UpdateUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthService_DeleteUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).DeleteUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.authservice.v1.AuthService/DeleteUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).DeleteUser(ctx, req.(*DeleteUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthService_UpdateUserNamespacePermissions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateUserNamespacePermissionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).UpdateUserNamespacePermissions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.authservice.v1.AuthService/UpdateUserNamespacePermissions",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).UpdateUserNamespacePermissions(ctx, req.(*UpdateUserNamespacePermissionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthService_CreateAPIKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateAPIKeyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).CreateAPIKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.authservice.v1.AuthService/CreateAPIKey",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).CreateAPIKey(ctx, req.(*CreateAPIKeyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthService_GetAPIKeys_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAPIKeysRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).GetAPIKeys(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.authservice.v1.AuthService/GetAPIKeys",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).GetAPIKeys(ctx, req.(*GetAPIKeysRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthService_GetAPIKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAPIKeyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).GetAPIKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.authservice.v1.AuthService/GetAPIKey",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).GetAPIKey(ctx, req.(*GetAPIKeyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthService_DeleteAPIKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteAPIKeyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).DeleteAPIKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.authservice.v1.AuthService/DeleteAPIKey",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).DeleteAPIKey(ctx, req.(*DeleteAPIKeyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _AuthService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "api.authservice.v1.AuthService",
	HandlerType: (*AuthServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetRole",
			Handler:    _AuthService_GetRole_Handler,
		},
		{
			MethodName: "GetRoles",
			Handler:    _AuthService_GetRoles_Handler,
		},
		{
			MethodName: "GetRolesByPermissions",
			Handler:    _AuthService_GetRolesByPermissions_Handler,
		},
		{
			MethodName: "GetUsers",
			Handler:    _AuthService_GetUsers_Handler,
		},
		{
			MethodName: "GetUser",
			Handler:    _AuthService_GetUser_Handler,
		},
		{
			MethodName: "InviteUsers",
			Handler:    _AuthService_InviteUsers_Handler,
		},
		{
			MethodName: "ResendUserInvite",
			Handler:    _AuthService_ResendUserInvite_Handler,
		},
		{
			MethodName: "UpdateUser",
			Handler:    _AuthService_UpdateUser_Handler,
		},
		{
			MethodName: "DeleteUser",
			Handler:    _AuthService_DeleteUser_Handler,
		},
		{
			MethodName: "UpdateUserNamespacePermissions",
			Handler:    _AuthService_UpdateUserNamespacePermissions_Handler,
		},
		{
			MethodName: "CreateAPIKey",
			Handler:    _AuthService_CreateAPIKey_Handler,
		},
		{
			MethodName: "GetAPIKeys",
			Handler:    _AuthService_GetAPIKeys_Handler,
		},
		{
			MethodName: "GetAPIKey",
			Handler:    _AuthService_GetAPIKey_Handler,
		},
		{
			MethodName: "DeleteAPIKey",
			Handler:    _AuthService_DeleteAPIKey_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/authservice/v1/service.proto",
}
